### ISSUE TITLE
Crash 1.18.1

### ISSUE THREAD

**Issue by GullyBunKus** [AlgorithmLX-Team/LiaVeres-Forge#6]
Forge 39.0.76
I would love to have this mod in my pack but it's crashing on startup. Removing the mod fixes it, heres the [latest.log](https://pastebin.com/Zwv1vsME)

**Comment by GullyBunKus** [comment]
The log says forge 39.0.66, but another mod required 39.0.76. Both versions crashed either way

**Comment by AlgorithmLX** [comment]
Hey! Can you please upload the crash log? It's just that not everything is usually written in the log. 

I want to warn you, I am currently unable to fix this bug/crash, due to the fact that my computer is broken(p.s. I live in Russia (You can say anything about me) and due to the sanctions, the prices for motherboards are very high

**Comment by GullyBunKus** [comment]
A crash log isn't generated. I just get sent back to the launcher, it says "This crash may be caused by invalid Java Runtime configuration. Check any custom configuration settings" if that's any help? It's ok if this can't be fixed immediately, I'm not in a rush and I'll be happy to wait for it :) Thank you for the reply as well!

**Comment by AlgorithmLX** [comment]
Hm.. Usually this error appears when Java is not properly configured. Have you tried running without LiaVeres?

**Comment by AlgorithmLX** [comment]
If you tried, and you still have an error, try starting not with CourseForge, but with a regular launcher, or, in extreme cases, try MultiMC

**Comment by GullyBunKus** [comment]
The same error occurred on the regular minecraft launcher, I gave MultiMC a try but couldn't get it to work. If you need it, I'll give it a try tomorrow. Sorry for all the trouble, and I hope I can help fix this

**Comment by GullyBunKus** [comment]
even removing all of my other mods and only using LiaVeres with forge, I get the same crash. Maybe this is something wrong on my end.

**Comment by AlgorithmLX** [comment]
Well, I have only one suggestion, reinstall Java

**Comment by AlgorithmLX** [comment]
And no need to apologize to me :)

**Comment by GullyBunKus** [comment]
Okay, so I just tried using LiaVeres 1.18.1-A1 instead of A3 and I got a crash report... I updated drivers, reinstalled java as you suggested, same error. https://pastebin.com/TbhJhfxe maybe this can help?

**Comment by AlgorithmLX** [comment]
🤔

**Comment by AlgorithmLX** [comment]
So, that's it, I understood what the mistake is, the mistake is in rarity. P.s. I did not immediately understand it, and did not immediately notice

**Comment by GullyBunKus** [comment]
That's alright, thank you for your patience and being very helpful :)

**Comment by AlgorithmLX** [comment]
I'll fix it this month. In the meantime, try downloading a newer or older version of the mod, because I only tested in IDE, but there is a special, test forge, so it may differ
